services:
  coachflow-web:
    image: ghcr.io/nordnat/coaching-page:latest
    container_name: coachflow-website
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.coachflow.rule=Host(`coachflow.com.pl`) || Host(`www.coachflow.com.pl`)"
      - "traefik.http.routers.coachflow.entrypoints=websecure"
      - "traefik.http.routers.coachflow.tls=true"
      - "traefik.http.routers.coachflow.tls.certresolver=letsencrypt"
      - "traefik.http.services.coachflow.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
