name: Deploy CoachFlow

# Akcja uruchomi się automatycznie po wrzuceniu (push) kodu na główną gałąź (main)
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
- name: Ping serwera z GitHuba
        run: nc -vz ${{ secrets.HOSTING_IP }} 22


      - name: SSH and Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTING_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Wejście do folderu z projektem na serwerze
            cd /docker/coachflow
            
            # 2. Pobranie najnowszych zmian z GitHuba
            git pull origin main
            
            # 3. Zbudowanie od nowa i restart wyłącznie kontenera coachflow
            docker-compose up -d --build coachflow
            